### ISSUE TITLE
(re-)Add RSS

### ISSUE THREAD

**Issue by sylvainemery** [ultrabug/ultrabug.fr#1]
Some people (like me) still use an RSS reader to get their news. Sadly, since you moved from Wordpress to MkDocs, you lost your RSS feed and discoverability.
There is an MkDocs extension to generate an RSS feed: https://guts.github.io/mkdocs-rss-plugin/
Have you already considered this extension?
Thanks!

**Comment by ultrabug** [comment]
Hello @sylvainemery :kissing_closed_eyes: 

Thanks for your interest in my content :1st_place_medal: 

Yep I have considered this extension but was not satisfied with the result at the time. Since I was fuzzing with a lot of other things at the time, I should probably reconsider it and add back RSS capabilities to my site.

AFAIR I was not happy because I could not target parts of the site, having a RSS on things other than my blog seemed pointless for instance.

I'll keep this in mind and will try to make it work again :crossed_fingers:

**Comment by sylvainemery** [comment]
Well, the extension has a `match_path` option that could solve this problem.
https://guts.github.io/mkdocs-rss-plugin/configuration/#filter-pages
It was added after your move to MkDocs, maybe that's why the extension didn't work for you at the time.

**Comment by ultrabug** [comment]
Thanks a lot for pointing that out indeed @sylvainemery , it works like a charm :)

<3

**Comment by ultrabug** [comment]
hmm well .. almost like a charm as the RSS feed built from Github Actions does not respect the articles dates...

I'll think about how to fix this.

**Comment by ultrabug** [comment]
Okay, got it working now :+1:
